### ISSUE TITLE
localhost:8888 can't be reached

### ISSUE THREAD

**Issue by braampje** [rreben/basket4py#4]
after running the vagrant up command localhost:8888 doesn't do anything. don't we have to port forward somehow the 8888 port? also, where in the files is 8888 defined as the notebook location?

Any other ideas what I can be doing wrong?

**Comment by rreben** [comment]
Sorry, I did not update the docs.

Pls, try `192.168.33.12:8888` instead. The vagrant guest machine is set up with 192.168.33.12 as ip.

**Comment by rreben** [comment]
The port for jupyter server is defined in:
`basket4py/provision/files/jupyter_notebook_config.py`

**Comment by rreben** [comment]
If it won't be working. Pls try `vagrant provision`. Pls post logfiles here, if you have any errors.

Pls provide feedback if this working for you.

**Comment by bramvslooten** [comment]
Hi I got it working this morning py adding a port forward for 8888 in the
vagrant file. Thanks for the feedback!

Bram

**Comment by rreben** [comment]
Thx for the feedback. I updated the docs
