### ISSUE TITLE
Password for Jupyter?

### ISSUE THREAD

**Issue by lderanja** [rreben/basket4py#5]
I got through all of the steps as listed, but when I go to the URL to open the Jupyter notebook, it asks me for a password. I can't find anything in the instructions addressing this. Here is a screenshot below. Thanks!
![image](https://user-images.githubusercontent.com/33321714/32333774-e74bf772-bfa5-11e7-9842-e4f93f10b791.png)

**Comment by rreben** [comment]
The password is "password". 

I need to add this to the documentation.

**Comment by lderanja** [comment]
Thank you!
